- name: set top right corner to lock screen
  # defaults read com.apple.dock | grep wvous
  # https://github.com/search?q=wvous+13&type=code
  shell: defaults write com.apple.dock wvous-tr-corner -int 13

# references
# - https://github.com/kentcdodds/dotfiles/blob/main/.macos