- name: install homebrew
  shell: 'yes | /bin/bash -c $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)'
  args:
    creates: /usr/local/bin/brew
  become: yes

- name: update homebrew
  homebrew:
    state: latest
    update_homebrew: yes

- name: tap homebrew/cask
  homebrew_tap:
    tap: homebrew/cask
    state: present

# firefox-nighty
- name: tap homebrew/cask-versions
  homebrew_tap:
    tap: homebrew/cask-versions
    state: present

- name: tap codeclimate/formulae
  homebrew_tap:
    tap: codeclimate/formulae
    state: present

# docker needs to be installed before codeclimate
- name: install docker desktop
  homebrew_cask:
    name:
      - docker

# loop is easier here to see output, maybe a little slower?
- name: install homebrew apps
  homebrew:
    name: '{{ item }}'
    state: latest
  loop:
    - awscli
    - codeclimate # requires docker running
    - coreutils
    - ffmpeg
    - findutils # AAXtoMP3
    - gnu-sed
    - grep # AAXtoMP3
    - jabba
    - kubectx
    - mediainfo # AAXtoMP3
    - mkcert
    - mysql
    - ocrmypdf # pdf ocr
    - pandoc # md to pdf
    - pdfsandwich # pdf ocr
    - rbenv
    - rename
    - romkatv/powerlevel10k/powerlevel10k
    - speedtest-cli
    - watchman
    - wget
    - shellcheck

- name: install homebrew cask apps
  homebrew_cask:
    name: '{{ item }}'
    state: latest
  become: yes # adobe-digital-editions
  loop:
    - 1password
    - 1password-cli
    - adobe-digital-editions
    - android-platform-tools
    - aws-vault
    - beyond-compare
    - calibre
    - datagrip
    - figma
    - firefox
    - firefox-nightly
    - flux
    - google-chrome
    - google-chrome-canary
    - google-drive
    - hyper
    - itsycal
    - microsoft-edge-dev
    - mysides
    - ngrok
    - opera
    - perimeter81
    - plex-media-server
    - rocket # emojis!
    - skitch
    - slack-beta
    - spotify
    - visual-studio
    - visual-studio-code
    - visual-studio-code-insiders
    - vlc
    - zeplin
    - zoom
    - basictex # pandoc
